### ISSUE TITLE
Redux Framework Export

### ISSUE THREAD

**Issue by justiny** [FrankM1/radium-one-click-demo-install#2]
The exported file created from Redux is a json file.  In the init.php file, the $theme_options_file_name is looking for a txt file.  Is it possible to link to the json file?  or is it necessary to convert the exported Redux options file to a text file?

Thanks!

**Comment by mmaumio** [comment]
Ok. I got a fix for it.

Yes. You can upload a .json file.
In that case all you have to do is:

Instead of unserializing the .json file 
$data = unserialize( trim($data, '###') );

decode the json file as an array
$data = trim($data, '###');
$data = json_decode( $data, true );

This should work with most of the options framework I believe.

**Comment by FrankM1** [comment]
Hi guys a redux extension is now available here https://github.com/Webcreations907/WBC-Importer-extension
